name: gitlog
version: '1.0.0'
config-version: 2
profile: gitlog
model-paths: [models]
test-paths: [tests]
macro-paths: [macros]
clean-targets: [target, dbt_packages]
models:
  gitlog:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table
